name: Compile LilyPond scores

on:
  push:
    paths:
      - '**.ly'
  pull_request:
    paths:
      - '**.ly'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyPDF2
          pip install reportlab

      - name: Install LilyPond fluidsynth and lame
        run: |
          sudo apt-get update
          sudo apt-get install -y lilypond fluidsynth fluid-soundfont-gm lame
          # Check lilypond version
          lilypond --version

      - name: Compile all LilyPond scores (PDF + MIDI)
        run: |
          mkdir -p output
          shopt -s nullglob
          find partitions -type f -name "*.ly" -print0 | while IFS= read -r -d '' file; do
          # for file in $(find partitions -name '*.ly'); do
            echo "Compiling ${file}..."
            base=$(basename "${file}" .ly)
            echo "Compiling variants for {$base}..."

            # PDF outputs
            lilypond -dcompile-diatonique -o "output/${base}_diatonique" "${file}"
            lilypond -dcompile-chromatique -o "output/${base}_chromatique" "${file}"

            # MIDI output
            lilypond --formats=midi -dcompile-midi -o "output/${base}" "${file}"
          done

      - name: Generate MP3 files from MIDI
        run: |
          shopt -s nullglob
          find output -type f -name "*.midi" -print0 | while IFS= read -r -d '' midi_file; do
            base=$(basename "${midi_file}" .midi)
            wav_file="output/${base}.wav"
            echo "Generating WAV for ${midi_file}..."
            fluidsynth -ni /usr/share/sounds/sf2/FluidR3_GM.sf2 "${midi_file}" -F "${wav_file}" -r 44100
            mp3_file="output/${base}.mp3"
            echo "Generating MP3 for ${wav_file}..."
            lame --preset standard "${wav_file}" "${mp3_file}"
            rm "${wav_file}"
          done

      - name: Generate index.html
        run: python generate_index.py

      - name: Merge PDF files
        run: python merge_pdf.py

      - name: Upload compiled files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: lilypond-outputs
          path: output/
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write # to publish to gh-pages
      pages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: lilypond-outputs
          path: site

      # - name: Generate simple index.html
      #   run: |
      #     echo "<h1>LilyPond Generated Files</h1><ul>" > site/index.html
      #     find site -type f | sed 's|site/||' | while read f; do
      #       echo "<li><a href=\"$f\">$f</a></li>" >> site/index.html
      #     done
      #     echo "</ul>" >> site/index.html

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
